### ISSUE TITLE
Error validation stopped working on 7.3

### ISSUE THREAD

**Issue by bartsidee** [dstepanov/coffeescript-netbeans#32]
Error validation is not working anymore on netbeans 7.3 (OSX, rhino, plugin 1.4)

There are no warning notification at the line numbers and on compilation I do not see the compile error but an error with the plugin:

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
    at coffeescript.nb.CoffeeScriptRhinoCompiler.compile(CoffeeScriptRhinoCompiler.java:59)
    at coffeescript.nb.CoffeeScriptAction$CompilerTask.compile(CoffeeScriptAction.java:236)
    at coffeescript.nb.CoffeeScriptAction$ConsoleOutputCompileTask.run(CoffeeScriptAction.java:193)
    at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)
```

**Comment by javatlacati** [comment]
Reported trough netbeans portal: https://netbeans.org/bugzilla/show_bug.cgi?id=268370
